IN-924 Investigate error with FTP file transfer
Why these changes are being introduced:
* The ftplib.storbinary method throws errors that suggest file
transfer has failed even when the Carbon run successfully uploads
an XML file to the Elements FTP server.

For the 'people' feed, it would log:
ftplib.error_temp: 425 Error while transfering data: ECONNABORTED - Connection aborted

For the 'articles' feed, it would log:
TimeoutError: The read operation timed out

These changes introduce cleaner error handling that avoid the error for
the 'people' feed and except' timeout errors that do not actually seem to
have a negative impact.

How this addresses that need:
* Remove custom storbinary method to resolve errors for 'people' feed
* Add try-except-finally code block to cleanly handle timeout errors for 'articles' feed

Side effects of this change:
* None

Relevant ticket(s):
* https://mitlibraries.atlassian.net/jira/software/c/projects/IN/boards/70?modal=detail&selectedIssue=IN-924